### ISSUE TITLE
"ERROR: 'feed-parser' could not be found!"

### ISSUE THREAD

**Issue by emmatebibyte** [ZeroX-DG/rsn#2]
I'm not sure if you're maintaining this anymore, but I'm running Arch 32-bit, and when I try and use cargo to install your package, it spits out the error in the title.

**Comment by ethanholz** [comment]
I had the same issue.

**Comment by phanirithvij** [comment]
I think the submodule is not set up correctly. @ZeroX-DG can it be fixed

**Comment by ZeroX-DG** [comment]
This project was a long time ago when I still don't know how to use Rust yet so the code is horrible and so I don't think I'll fix this issue. The library that I used was this one:
https://crates.io/crates/feed-rs

And you can easily make a similar project using tui-rs if you're interested:
https://github.com/fdehau/tui-rs
